import { BRAND } from "@/lib/brand"
import type { Account, Activity, CrmSnapshot, FollowUp, Lead, Quote, Staff } from "./types"
import { segmentFromTrade } from "./labels"

function withArchitectContact<
  T extends {
    architectName: string
    architectFirm: string
    architectPhone?: string
    architectEmail?: string
  },
>(row: T): T & { architectPhone: string; architectEmail: string } {
  return {
    ...row,
    architectPhone: row.architectPhone ?? "",
    architectEmail: row.architectEmail ?? "",
  }
}

export const STAFF: Staff[] = [
  {
    id: "st-maryam",
    name: "Priya Menon",
    role: "Director",
    photoSeed: "shw-priya-menon",
  },
  {
    id: "st-yusuf",
    name: "Yusuf Rahman",
    role: "Contractor desk",
    photoSeed: "shw-yusuf-rahman",
  },
  {
    id: "st-laila",
    name: "Laila Hassan",
    role: "Projects",
    photoSeed: "shw-laila-hassan",
  },
  {
    id: "st-sandeep",
    name: "Sandeep Nair",
    role: "Counter",
    photoSeed: "shw-sandeep-nair",
  },
]

const leads: Lead[] = [
  {
    id: "ld-01",
    ticket: "TH-2409-1842",
    company: "Al Noor Contracting",
    contactName: "Rashid Al Marri",
    contactRole: "Procurement",
    phone: "+91 98 418 2291",
    whatsapp: "+91 98 418 2291",
    email: "rashid.m@alnoorcon.in",
    city: "Chennai",
    area: "Ambattur",
    source: "site_visit",
    tradeType: "contractor",
    lines: ["plumbing", "fasteners", "tools"],
    estimatedValue: 186400,
    stage: "quoted",
    ownerId: "st-yusuf",
    createdAt: "2026-09-02T08:14:00.000Z",
    updatedAt: "2026-09-13T11:20:00.000Z",
    nextAction: {
      kind: "call",
      dueAt: "2026-09-14T09:00:00.000Z",
      note: "Confirm PPR pipe sizes for Block C",
    },
    brief:
      "Villa compound in Velachery. Needs PPR, valves, and site tools for 18 units. Asking for staged delivery.",
    accountId: null,
    lostReason: null,
    architectName: "Kavitha Menon",
    architectFirm: "Studio North",
  },
  {
    id: "ld-02",
    ticket: "TH-2409-1847",
    company: "Walk-in: Fatima Koya",
    contactName: "Fatima Koya",
    contactRole: "Owner",
    phone: "+91 97 902 1144",
    whatsapp: "+91 97 902 1144",
    email: "",
    city: "Coimbatore",
    area: "RS Puram",
    source: "walk_in",
    tradeType: "homeowner",
    lines: ["paint", "electrical"],
    estimatedValue: 2140,
    stage: "new",
    ownerId: "st-sandeep",
    createdAt: "2026-09-14T06:42:00.000Z",
    updatedAt: "2026-09-14T06:42:00.000Z",
    nextAction: {
      kind: "follow_up",
      dueAt: "2026-09-14T15:00:00.000Z",
      note: "Send Jotun colour chips on WhatsApp",
    },
    brief:
      "Kitchen repaint plus two extra sockets. Came in during lunch rush. Left with sample cards.",
    accountId: null,
    lostReason: null,
    architectName: "",
    architectFirm: "",
  },
  {
    id: "ld-03",
    ticket: "TH-2409-1831",
    company: "Horizon Fitout LLC",
    contactName: "Anjali Menon",
    contactRole: "Project manager",
    phone: "+91 96 773 8801",
    whatsapp: "+91 96 773 8801",
    email: "anjali@horizonfitout.com",
    city: "Mumbai",
    area: "Andheri",
    source: "referral",
    tradeType: "fitout",
    lines: ["electrical", "hvac", "safety"],
    estimatedValue: 92400,
    stage: "contacted",
    ownerId: "st-laila",
    createdAt: "2026-08-28T10:05:00.000Z",
    updatedAt: "2026-09-12T16:40:00.000Z",
    nextAction: {
      kind: "visit",
      dueAt: "2026-09-15T07:30:00.000Z",
      note: "Measure DB room at clinic fit-out, Whitefield",
    },
    brief:
      "Referred by Al Noor. Clinic fit-out, 340 sqm. Wants one supplier for boards, cable, and PPE.",
    accountId: null,
    lostReason: null,
    architectName: "Ravi Iyer",
    architectFirm: "Atelier Line",
  },
  {
    id: "ld-04",
    ticket: "TH-2409-1826",
    company: "Gulf Bolt Traders",
    contactName: "Imran Qureshi",
    contactRole: "Owner",
    phone: "+91 95 221 4470",
    whatsapp: "+91 95 221 4470",
    email: "imran@gulfbolt.in",
    city: "Chennai",
    area: "Guindy",
    source: "phone",
    tradeType: "retailer",
    lines: ["fasteners", "tools"],
    estimatedValue: 41200,
    stage: "contacted",
    ownerId: "st-maryam",
    createdAt: "2026-09-08T12:18:00.000Z",
    updatedAt: "2026-09-11T09:10:00.000Z",
    nextAction: {
      kind: "quote",
      dueAt: "2026-09-16T10:00:00.000Z",
      note: "Grade 8.8 hex bolt pallet price",
    },
    brief:
      "Small fastener shop restocking from us instead of the wholesale market. Wants monthly pallet, net 30.",
    accountId: null,
    lostReason: null,
    architectName: "",
    architectFirm: "",
  },
  {
    id: "ld-05",
    ticket: "TH-2409-1819",
    company: "Shams Electrical Works",
    contactName: "Nasser Al Suwaidi",
    contactRole: "Foreman",
    phone: "+91 98 667 0912",
    whatsapp: "+91 98 667 0912",
    email: "nasser.shams@gmail.com",
    city: "Delhi",
    area: "Okhla",
    source: "whatsapp",
    tradeType: "subcontractor",
    lines: ["electrical"],
    estimatedValue: 67850,
    stage: "hold",
    ownerId: "st-yusuf",
    createdAt: "2026-08-19T07:55:00.000Z",
    updatedAt: "2026-09-09T13:02:00.000Z",
    nextAction: {
      kind: "call",
      dueAt: "2026-09-17T08:00:00.000Z",
      note: "Waiting on consultant cable spec",
    },
    brief:
      "Warehouse job on hold until consultant signs XLPE vs PVC. Quote already out for 240mm.",
    accountId: null,
    lostReason: null,
    architectName: "",
    architectFirm: "",
  },
  {
    id: "ld-06",
    ticket: "TH-2409-1851",
    company: "Bayti Maintenance",
    contactName: "George Varghese",
    contactRole: "Supervisor",
    phone: "+91 94 304 7721",
    whatsapp: "+91 94 304 7721",
    email: "george@bayti.in",
    city: "Mumbai",
    area: "Bandra",
    source: "web",
    tradeType: "contractor",
    lines: ["plumbing", "hvac"],
    estimatedValue: 9800,
    stage: "new",
    ownerId: "st-sandeep",
    createdAt: "2026-09-13T18:22:00.000Z",
    updatedAt: "2026-09-13T18:22:00.000Z",
    nextAction: {
      kind: "whatsapp",
      dueAt: "2026-09-14T11:00:00.000Z",
      note: "Confirm building access for sample pickup",
    },
    brief:
      "Website form. Recurring A/C drain and pump work across three buildings.",
    accountId: null,
    lostReason: null,
    architectName: "",
    architectFirm: "",
  },
  {
    id: "ld-07",
    ticket: "TH-2409-1804",
    company: "Municipality Stores, Coimbatore",
    contactName: "Khalid Al Shamsi",
    contactRole: "Store keeper",
    phone: "+91 44 701 4400",
    whatsapp: "",
    email: "k.alshamsi@ajman.in",
    city: "Coimbatore",
    area: "Gandhipuram",
    source: "phone",
    tradeType: "institution",
    lines: ["safety", "tools", "building"],
    estimatedValue: 154000,
    stage: "quoted",
    ownerId: "st-laila",
    createdAt: "2026-08-11T09:30:00.000Z",
    updatedAt: "2026-09-10T14:18:00.000Z",
    nextAction: {
      kind: "follow_up",
      dueAt: "2026-09-18T10:00:00.000Z",
      note: "Tender committee sits Thursday",
    },
    brief:
      "Annual PPE and hand-tool tender. Need fire safety certificates on file.",
    accountId: null,
    lostReason: null,
    architectName: "",
    architectFirm: "",
  },
  {
    id: "ld-08",
    ticket: "TH-2409-1798",
    company: "Red Palm Interiors",
    contactName: "Sara Al Ketbi",
    contactRole: "Buyer",
    phone: "+91 93 119 6630",
    whatsapp: "+91 93 119 6630",
    email: "sara@redpalm.in",
    city: "Mumbai",
    area: "Lower Parel",
    source: "referral",
    tradeType: "fitout",
    lines: ["paint", "electrical", "fasteners"],
    estimatedValue: 33100,
    stage: "contacted",
    ownerId: "st-laila",
    createdAt: "2026-09-05T15:41:00.000Z",
    updatedAt: "2026-09-12T08:05:00.000Z",
    nextAction: {
      kind: "quote",
      dueAt: "2026-09-15T12:00:00.000Z",
      note: "Low-VOC paint list for hotel rooms",
    },
    brief:
      "Boutique hotel refresh, 42 rooms. Colour deck already chosen. Needs next-day delivery.",
    accountId: null,
    lostReason: null,
    architectName: "Diya Kapoor",
    architectFirm: "Kapoor & Co.",
  },
  {
    id: "ld-09",
    ticket: "TH-2409-1782",
    company: "Steel Arc Fabrication",
    contactName: "Biju Thomas",
    contactRole: "Workshop in-charge",
    phone: "+91 98 233 9188",
    whatsapp: "+91 98 233 9188",
    email: "biju@steelar.in",
    city: "Chennai",
    area: "Sriperumbudur",
    source: "walk_in",
    tradeType: "subcontractor",
    lines: ["fasteners", "tools", "safety"],
    estimatedValue: 27650,
    stage: "won",
    ownerId: "st-yusuf",
    createdAt: "2026-07-22T11:00:00.000Z",
    updatedAt: "2026-09-01T10:12:00.000Z",
    nextAction: null,
    brief:
      "Converted after three workshop visits. Monthly consumables account opened.",
    accountId: "AC-108",
    lostReason: null,
    architectName: "",
    architectFirm: "",
  },
  {
    id: "ld-10",
    ticket: "TH-2409-1771",
    company: "Oasis Plumbing",
    contactName: "Hassan Farooq",
    contactRole: "Owner",
    phone: "+91 97 441 2290",
    whatsapp: "+91 97 441 2290",
    email: "oasis.plumb@gmail.com",
    city: "Kochi",
    area: "Kakkanad",
    source: "whatsapp",
    tradeType: "contractor",
    lines: ["plumbing"],
    estimatedValue: 15800,
    stage: "lost",
    ownerId: "st-sandeep",
    createdAt: "2026-07-09T13:20:00.000Z",
    updatedAt: "2026-08-21T09:44:00.000Z",
    nextAction: null,
    brief: "Wanted 60-day credit on a first order. Could not match terms.",
    accountId: null,
    lostReason: "Credit terms",
    architectName: "",
    architectFirm: "",
  },
  {
    id: "ld-11",
    ticket: "TH-2409-1853",
    company: "Al Falah School Maintenance",
    contactName: "Priya Nambiar",
    contactRole: "Facilities",
    phone: "+91 44 558 1020",
    whatsapp: "+91 98 889 4412",
    email: "facilities@alfalahschool.in",
    city: "Chennai",
    area: "Velachery",
    source: "phone",
    tradeType: "institution",
    lines: ["electrical", "safety", "paint"],
    estimatedValue: 22400,
    stage: "contacted",
    ownerId: "st-maryam",
    createdAt: "2026-09-11T07:12:00.000Z",
    updatedAt: "2026-09-13T09:30:00.000Z",
    nextAction: {
      kind: "visit",
      dueAt: "2026-09-16T06:00:00.000Z",
      note: "Walk the summer maintenance list with facilities",
    },
    brief:
      "School closed for summer works. Lights, fire extinguishers, corridor paint.",
    accountId: null,
    lostReason: null,
    architectName: "",
    architectFirm: "",
  },
  {
    id: "ld-12",
    ticket: "TH-2409-1840",
    company: "Meadows Villa 42",
    contactName: "Omar Haddad",
    contactRole: "Homeowner",
    phone: "+91 98 712 6634",
    whatsapp: "+91 98 712 6634",
    email: "omar.haddad@icloud.com",
    city: "Mumbai",
    area: "Powai",
    source: "walk_in",
    tradeType: "homeowner",
    lines: ["plumbing", "tools"],
    estimatedValue: 760,
    stage: "contacted",
    ownerId: "st-sandeep",
    createdAt: "2026-09-10T16:05:00.000Z",
    updatedAt: "2026-09-10T16:40:00.000Z",
    nextAction: {
      kind: "call",
      dueAt: "2026-09-14T17:00:00.000Z",
      note: "Plumber coming Saturday, confirm stock",
    },
    brief: "Leaking outdoor tap and a new hose reel. Small but repeat customer.",
    accountId: null,
    lostReason: null,
    architectName: "",
    architectFirm: "",
  },
].map(withArchitectContact) as Lead[]

const accounts: Account[] = [
  {
    id: "AC-108",
    name: "Steel Arc Fabrication",
    tradeType: "subcontractor",
    segment: segmentFromTrade("subcontractor"),
    contactName: "Biju Thomas",
    phone: "+91 98 233 9188",
    email: "biju@steelar.in",
    city: "Chennai",
    area: "Sriperumbudur",
    address: "Sriperumbudur, Chennai",
    ownerId: "st-yusuf",
    creditLimit: 45000,
    paymentTerms: "net_30",
    gstin: "100294817200003",
    openedAt: "2026-09-01T10:12:00.000Z",
    sourceLeadId: "ld-09",
    notes: "Pays on the 28th. Prefers Friday afternoon pickup.",
    architectName: "",
    architectFirm: "",
  },
  {
    id: "AC-102",
    name: `${BRAND.name} (internal)`,
    tradeType: "contractor",
    segment: segmentFromTrade("contractor"),
    contactName: "Priya Menon",
    phone: "+91 44 532 1100",
    email: BRAND.contactEmail,
    city: "Chennai",
    area: "Ambattur Industrial Estate",
    address: "Ambattur Industrial Estate, Chennai",
    ownerId: "st-maryam",
    creditLimit: 250000,
    paymentTerms: "net_45",
    gstin: "100118226400003",
    openedAt: "2024-01-14T08:00:00.000Z",
    sourceLeadId: null,
    notes: "House account for own site jobs. Do not mix with walk-in till.",
    architectName: "",
    architectFirm: "",
  },
  {
    id: "AC-104",
    name: "Coastal MEP",
    tradeType: "contractor",
    segment: segmentFromTrade("contractor"),
    contactName: "Faisal Karim",
    phone: "+91 98 901 2287",
    email: "faisal@coastalmep.in",
    city: "Mumbai",
    area: "Taloja",
    address: "Taloja, Mumbai",
    ownerId: "st-laila",
    creditLimit: 120000,
    paymentTerms: "net_30",
    gstin: "100552119800003",
    openedAt: "2025-11-03T09:20:00.000Z",
    sourceLeadId: null,
    notes: "Approved account. Two cheques in file.",
    architectName: "",
    architectFirm: "",
  },
].map(withArchitectContact) as Account[]

const quotes: Quote[] = [
  {
    id: "qt-01",
    leadId: "ld-01",
    accountId: null,
    number: "Q-2418",
    amount: 179650,
    status: "sent",
    sentAt: "2026-09-13T11:20:00.000Z",
    validUntil: "2026-09-27T00:00:00.000Z",
    note: "Staged delivery, three drops. Excludes labour.",
  },
  {
    id: "qt-02",
    leadId: "ld-07",
    accountId: null,
    number: "Q-2409",
    amount: 151880,
    status: "sent",
    sentAt: "2026-09-10T14:18:00.000Z",
    validUntil: "2026-10-10T00:00:00.000Z",
    note: "Tender pack with certificates.",
  },
  {
    id: "qt-03",
    leadId: "ld-05",
    accountId: null,
    number: "Q-2394",
    amount: 66820,
    status: "revised",
    sentAt: "2026-09-01T08:00:00.000Z",
    validUntil: "2026-09-20T00:00:00.000Z",
    note: "Revised after PVC option added.",
  },
  {
    id: "qt-04",
    leadId: "ld-09",
    accountId: "AC-108",
    number: "Q-2381",
    amount: 18420,
    status: "accepted",
    sentAt: "2026-08-28T10:00:00.000Z",
    validUntil: "2026-09-11T00:00:00.000Z",
    note: "Fastener pallet — accepted and collected.",
  },
]

const activities: Activity[] = [
  {
    id: "ac-01",
    leadId: "ld-01",
    accountId: null,
    type: "visit",
    body: "Yusuf walked Block C with Rashid. Confirmed 25mm and 32mm PPR, not 20mm.",
    at: "2026-09-12T07:40:00.000Z",
    authorId: "st-yusuf",
  },
  {
    id: "ac-02",
    leadId: "ld-01",
    accountId: null,
    type: "quote",
    body: "Quote Q-2418 sent on WhatsApp and email.",
    at: "2026-09-13T11:20:00.000Z",
    authorId: "st-yusuf",
  },
  {
    id: "ac-03",
    leadId: "ld-02",
    accountId: null,
    type: "note",
    body: "Logged at counter. Fatima will decide after checking the colour with her contractor.",
    at: "2026-09-14T06:42:00.000Z",
    authorId: "st-sandeep",
  },
  {
    id: "ac-04",
    leadId: "ld-03",
    accountId: null,
    type: "call",
    body: "Anjali confirmed clinic handover is 12 October. Needs boards in week one.",
    at: "2026-09-12T16:40:00.000Z",
    authorId: "st-laila",
  },
  {
    id: "ac-05",
    leadId: "ld-09",
    accountId: "AC-108",
    type: "convert",
    body: "Won. Opened account AC-108, net 30, limit ₹45,000.",
    at: "2026-09-01T10:12:00.000Z",
    authorId: "st-yusuf",
  },
  {
    id: "ac-06",
    leadId: "ld-05",
    accountId: null,
    type: "stage",
    body: "Moved to on hold. Consultant has not signed cable spec.",
    at: "2026-09-09T13:02:00.000Z",
    authorId: "st-yusuf",
  },
  {
    id: "ac-07",
    leadId: "ld-04",
    accountId: null,
    type: "whatsapp",
    body: "Imran sent last three months' fastener offtake. Looking like 8 pallets.",
    at: "2026-09-11T09:10:00.000Z",
    authorId: "st-maryam",
  },
  {
    id: "ac-08",
    leadId: "ld-07",
    accountId: null,
    type: "note",
    body: "Fire safety certificates attached to the tender folder.",
    at: "2026-09-10T14:05:00.000Z",
    authorId: "st-laila",
  },
]

const followUps: FollowUp[] = [
  {
    id: "fu-01",
    accountId: "AC-108",
    leadId: null,
    kind: "repeat_order",
    dueAt: "2026-09-16T09:00:00.000Z",
    note: "Monthly fastener pallet — confirm qty before Thursday",
    doneAt: null,
    createdAt: "2026-09-10T08:00:00.000Z",
    authorId: "st-yusuf",
  },
  {
    id: "fu-02",
    accountId: "AC-102",
    leadId: null,
    kind: "quote_pending",
    dueAt: "2026-09-15T11:00:00.000Z",
    note: "Chase acceptance on last mortise-lock quote",
    doneAt: null,
    createdAt: "2026-09-12T14:00:00.000Z",
    authorId: "st-laila",
  },
  {
    id: "fu-03",
    accountId: null,
    leadId: "ld-01",
    kind: "call",
    dueAt: "2026-09-14T09:00:00.000Z",
    note: "Confirm PPR pipe sizes for Block C",
    doneAt: null,
    createdAt: "2026-09-13T11:20:00.000Z",
    authorId: "st-yusuf",
  },
]

export const SEED: CrmSnapshot = {
  staff: STAFF,
  leads,
  activities,
  quotes,
  accounts,
  followUps,
}